version: 2.1

workflows:
  main-wf:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/python:3.7.17
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              build-essential \
              curl \
              libssl-dev \
              libbz2-dev \
              libreadline-dev \
              libsqlite3-dev \
              libncursesw5-dev \
              libxml2-dev \
              libxmlsec1-dev \
              libffi-dev \
              liblzma-dev \
              tk-dev \
              xz-utils \
              zlib1g-dev
            pip install -r requirements.txt
      - run:
          name: "Run Tests"
          command: ./manage.py test
